.gitignore, Source/Reactions/Reactions.csproj
=> Explicit reference to System.Text.Encoding.Extensions

Source/Reactions/Applications/DeployableProjection.cs
- Added Deployable immediate projection definition.
=> Adding deployable immediate projection

Source/Reactions/Applications/Pulumi/PulumiOperations.cs, Source/Reactions/Applications/Pulumi/PulumiOperationsLogMessages.cs
- Adding error message to the log if failing during Pulumi Operations.
=> Adding proper error message when operations are failing

Docker/Production/Dockerfile
- Adding the path to Pulumi to the PATH environment variable
=> Adding Pulumi to the path in /etc/environment

Docker/Production/Dockerfile
- Fixing so that we actually export the path to Pulumi, not just setting PATH.
=> Fix so that we export the path

Docker/Production/Dockerfile
- Hopefully we get Pulumi in the path with this release.
=> Moving Pulumi path into .profile file for root

Docker/Production/Dockerfile
- Hopefully we have an improved pipeline that is much faster.
=> Trying out if the new pipeline works and is faster

.dockerignore, Docker/Kernel/dockerize.sh, Source/Environment/docker-compose.yml, Source/Reactions/Applications/Pulumi/PulumiOperations.cs, Source/Web/package.json, Versions.props
=> Upgrade Cratis

Source/Reactions/Applications/Pulumi/PulumiOperations.cs
- Moving configuration of environment variables for Pulumi into the program.
=> Moving environment variables into InlineProgramArgs

.github/workflows/publish.yml, Source/Reactions/Applications/Pulumi/PulumiOperations.cs
- Fixing cache keys used for sharing data between jobs so that we are actually building new things
=> Fixing cache keys

Source/Bootstrap/Program.cs, Source/Reactions/Applications/Pulumi/ApplicationMongoDBPulumiExtensions.cs, Source/Reactions/Applications/Pulumi/PulumiOperations.cs, Source/Reactions/Applications/Pulumi/PulumiOperationsLogMessages.cs
- For debugging purposes; adding logging of application content and settings content.
=> Config-output

APIDesign.md, Source/Bootstrap/NullStacks.cs, Source/Bootstrap/Program.cs, Source/Reactions/Applications/Pulumi/IStacks.cs, Source/Reactions/Applications/Pulumi/PulumiOperations.cs, Source/Reactions/Applications/Pulumi/PulumiOperationsLogMessages.cs, Source/Reactions/Applications/Pulumi/StackDeploymentForApplication.cs, Source/Reactions/Applications/Pulumi/Stacks.cs
- Persisting stack per application and importing it for every operation.
=> Adding persistence of stack deployments, since the cloud will be stateless

.github/workflows/dotnet-build.yml, Docker/Kernel/dockerize.sh, README.md, Source/Bootstrap/AppManagerApi.cs, Source/Bootstrap/Program.cs, Source/Domain/Applications/Applications.cs, Source/Environment/docker-compose.yml, Source/Reactions/Applications/Pulumi/ApplicationContainerAppsManagedEnvironmentExtensions.cs, Source/Reactions/Applications/Pulumi/ApplicationMongoDBPulumiExtensions.cs, Source/Reactions/Applications/Pulumi/ApplicationNetworkPulumiExtensions.cs, Source/Reactions/Applications/Pulumi/PulumiOperationsLogMessages.cs, Source/Reactions/Applications/Pulumi/PulumiStackDefinitions.cs, Source/Web/API/applications/SetStack.ts, Source/Web/package.json, Versions.props
- Payload expectations for Stack when sending it from something like the Bootstrapper
=> Switching strategy for sending JSON Stack representation

Source/Domain/Applications/Applications.cs
=> Removing unused usings

Source/Reactions/Applications/ApplicationResourcesCoordinator.cs, Source/Reactions/Applications/ApplicationResourcesCoordinatorLogMessages.cs
- Making all Pulumi operations asynchronous.
=> Make all Pulumi operations async

Source/Reactions/Applications/Pulumi/MicroserviceStoragePulumiExtensions.cs
- Getting existing fileshare for Microservice, if not exists create it
=> Getting fileshare before trying to create it

Source/Bootstrap/Program.cs, Source/Reactions/Applications/Pulumi/MicroserviceStoragePulumiExtensions.cs
- Reverting on getting existing fileshare before creating. Doesn't really work.
=> Revert on getting existing fileshare

Source/Reactions/Applications/ApplicationResourcesCoordinator.cs
- Passing along the Microservice when updating deployables image. Stop the resource mayhem.
=> Passing along microservice on image updates

Source/Bootstrap/Program.cs, Source/Reactions/Applications/Pulumi/PulumiOperations.cs
- Import the Microservice and not the Application when updating a microservice.
=> Getting Microservice stack when it is a microservice

Source/Reactions/Applications/Pulumi/PulumiOperations.cs
- Consistently using Microservice if it is a microservice update.
=> Forward Microservice to CreateStack

Docker/Kernel/dockerize.sh, Source/Environment/docker-compose.yml, Source/Web/package.json, Versions.props
- Config path for deployables is now overridable
- Introducing resource system
- Implemented Service Bus as resource
- Outbox -> Inbox configuration in place
- VNET configuration done
- Azure AD issuer made configurable, we can now chose multi/single tenant
- Custom domains up and running
=> Upgraded to latest Cratis

.github/workflows/diagnostics.yml
- Fixing path for GitHub action that builds the diagnostics image.
=> Fixing folder for dockerfile

Source/Bootstrap/AzureConfig.cs
Testing out the continuous deployment feature.
=> Trigger build

.editorconfig, Directory.Packages.props, Source/Bootstrap/ConfigVariablesExtensions.cs, Source/Bootstrap/ManagementConfig.cs, Source/Reactions/Applications/ApplicationEnvironmentWithArtifacts.cs, Source/Reactions/Applications/ApplicationEnvironmentWithArtifactsProjection.cs, Source/Reactions/Applications/Certificate.cs, Source/Reactions/Applications/Pulumi/ApplicationContainerAppsManagedEnvironmentExtensions.cs, Source/Reactions/Applications/Pulumi/ApplicationEnvironmentCertificates.cs, Source/Reactions/Applications/Pulumi/ApplicationEnvironmentResult.cs, Source/Reactions/Applications/Pulumi/ApplicationIngressPulumiExtensions.cs, Source/Reactions/Applications/Pulumi/ApplicationManagedEnvironmentExtensions.cs, Source/Reactions/Applications/Pulumi/ContainerAppResult.cs, Source/Reactions/Applications/Pulumi/DuplicateCertificateIdsUsedInConfiguration.cs, Source/Reactions/Applications/Pulumi/IPulumiStackDefinitions.cs, Source/Reactions/Applications/Pulumi/IngressResult.cs, Source/Reactions/Applications/Pulumi/MicroserviceContainerAppPulumiExtensions.cs, Source/Reactions/Applications/Pulumi/PulumiOperations.cs, Source/Reactions/Applications/Pulumi/PulumiStackDefinitions.cs, Source/Reactions/Applications/Pulumi/Resources/Cratis/CratisResourceRenderer.cs, Source/Reactions/Applications/Pulumi/Resources/ServiceBus/ServiceBusResourceRenderer.cs
- Updated to pulumi azure v2 module
- Added support for managed certificates in Container App Environment
=> Added support for managed certificates in Container App Environment

Source/Reactions/Applications/Pulumi/ApplicationIngressPulumiExtensions.cs
- Fixed ingress configuration to work with the updated ingress middleware
=> Update to reflect ingress config changes

Source/Reactions/Applications/Templates/SpecifiedTenantResolutionOptions.cs
- Corrected propertyname in SpecifiedTenantResolutionOptions
=> Correction for wrong propertyname

Directory.Packages.props, Source/Bootstrap/Program.cs, Source/Reactions/Applications/ApplicationEnvironmentWithArtifacts.cs, Source/Reactions/Applications/Pulumi/ApplicationEnvironmentResult.cs, Source/Reactions/Applications/Pulumi/ApplicationIngressPulumiExtensions.cs, Source/Reactions/Applications/Pulumi/ApplicationMongoDBPulumiExtensions.cs, Source/Reactions/Applications/Pulumi/ApplicationNetworkPulumiExtensions.cs, Source/Reactions/Applications/Pulumi/MicroserviceContainerAppPulumiExtensions.cs, Source/Reactions/Applications/Pulumi/PulumiOperations.cs, Source/Reactions/Applications/Pulumi/Resources/Cratis/CratisResourceRenderer.cs, Source/Reactions/Applications/VnetConfig.cs
Fixes and enhancements needed while setting up new environment.
Improved ssl for ingress hostname/domain bit, but it is still necessary to run once without the certificateId to register the hostname - and then run again with a certificateId to create that.
- Supports configurable vnet ip-ranges.
- Kernel container is now set up with more resources.
=> Fixes and enhancements needed while setting up new environment.
